extends: default
rules:
  document-start: {present: false}
  line-length:
    max: 132
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
    ignore: |
      /.github/workflows/lint.yaml
  truthy:
    ignore: |
      /.github/workflows/
  indentation:
    indent-sequences: consistent
