---
apiVersion: v1
kind: Service
metadata:
  name: oga-butler-enqueue
  labels:
    app: enqueue
  annotations:
    metallb.universe.tf/address-pool: sdf-services
spec:
  type: LoadBalancer
  ports:
  - name: enqueue-webhook
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: enqueue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oga-butler-enqueue
  labels:
    app: enqueue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enqueue
  template:
    metadata:
      labels:
        app: enqueue
    spec:
      containers:
      - name: enqueue
        image: "ghcr.io/lsst-dm/oga-butler-enqueue:latest"
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: oga-butler-redis-common
              key: redis_host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oga-butler-enqueue-secret
              key: redis_password
        - name: NOTIFICATION_SECRET
          valueFrom:
            secretKeyRef:
              name: oga-butler-enqueue-secret
              key: notification_secret
        resources:
          limits:
            cpu: "1"
